#pragma once
#include <xtl.h>
#include <xboxmath.h>
#include <stdio.h>
#include <fstream>
#include <sstream>
#include <time.h>
#include <map>
#include "XConfig.h"
#include <xkelib.h>
#include <xuiapp.h>
#include "Tools.h"
#include "KVvault.h"
#include "system.h"
#include "Title.h"
#include "XOSC.h"
#include "Detour.h"
#include <vector>
#include "BootLoader.h"

